### ISSUE TITLE
Need level-date for Location Level

### ISSUE THREAD

**Issue by inguyen314** [USACE/cwms-data-api#662]
I need to extract the location level (Record Stage) level-date. 

Here is my SQL statement.

```sql 
select location_id
    ,location_level_id
    ,level_date
    ,constant_level
    ,level_unit
from CWMS_20.AV_LOCATION_LEVEL
where specified_level_id = 'Record Stage' and location_id = cwms_util.split_text('St Louis-Mississippi.Stage.Inst.30Minutes.0.lrgsShef-rev', 1, '.') and unit_system = 'EN'

```

The SQL above returns a `constant_level = 49.58` and `level_date =  01-Aug-93` _(these are what i need)_

I cannot replicate this with CDA:
![image](https://github.com/USACE/cwms-data-api/assets/102250746/fa49cf0c-9838-463d-af17-1b6212365512)

CDA does not return the correct "level-date"?
https://water.usace.army.mil/cwms-data/levels/St%20Louis-Mississippi.Stage.Inst.0.Record%20Stage?office=MVS&effective-date=2024-01-01T08:00:00&unit=ft

This is the payload i'm seeing from CDA:
```json
 "office-id": "MVS",
  "location-level-id": "St Louis-Mississippi.Stage.Inst.0.Record Stage",
  "seasonal-values": [],
  "constant-value": 49.58,
  "level-units-id": "ft",
  "level-date": "2024-01-01T08:00:00Z",
  "interval-months": 0,
  "interval-minutes": 0,
  "attribute-units-id": "ft"
```

```bash
curl -X 'GET' \
  'https://cwms-data.usace.army.mil/cwms-data/levels/St%20Louis-Mississippi.Stage.Inst.0.Record%20Stage?office=MVS&effective-date=2024-05-23T00%3A00&unit=ft' \
  -H 'accept: application/json;version=2'
```

thanks

**Comment by rma-rripken** [comment]
This issue needs to be revisited in more depth but I noticed that the getOne and getAlll end-points currently go thru some slightly different logic and the getAll appears to return the date you want but it might only work for SI until servers are updated.

**Comment by inguyen314** [comment]
I need to grab the "Effective Date" which is 01Aug1993. 

```bash
curl -X 'GET' \
  'T7:8243/mvs-data/levels/St%20Louis-Mississippi.Stage.Inst.0.Record%20Stage?office=MVS&effective-date=2025-03-01T12%3A00%3A00Z&unit=m' \
  -H 'accept: application/json;version=2'
```
it return this 

```json 
{
  "office-id": "MVS",
  "location-level-id": "St Louis-Mississippi.Stage.Inst.0.Record Stage",
  "constant-value": 15.111984,
  "level-units-id": "m",
  "level-date": "2025-03-01T12:00:00Z",
  "attribute-units-id": "m",
  "seasonal-values": []
}
```

![Image](https://github.com/user-attachments/assets/08b36905-7485-445e-af5d-e61a57303830)

**Comment by MikeNeilson** [comment]
I believe this has been corrected, please try it again with the latest version: https://github.com/USACE/cwms-data-api/releases/tag/2025.03.05

**Comment by inguyen314** [comment]
I updated to version  2025.03.05 but still not working. 

curl -X 'GET' \
  'https://coe-mvsuwa04mvs.mvs.usace.army.mil:8243/mvs-data/levels/St%20Louis-Mississippi.Stage.Inst.0.Record%20Stage?office=MVS&effective-date=2025-03-10T12%3A00%3A00Z&unit=ft' \
  -H 'accept: application/json;version=2'

{
  "office-id": "MVS",
  "location-level-id": "St Louis-Mississippi.Stage.Inst.0.Record Stage",
  "constant-value": 49.57999999999999,
  "level-units-id": "ft",
  "level-date": "2025-03-10T12:00:00Z",
  "attribute-units-id": "ft",
  "seasonal-values": []
}


I need the payload to return the effective date of "01Aug1993" , see image above.
